# Introduction

This notebook has some snippets of code that might be useful to get you started on the Save the Children Humanitarian insights DataDive challenge. For more details see [project brief](https://docs.google.com/document/d/1g7Kkfnxy_XKpF1Hn7fmCbvA6jqCQhsvM5B2iEJ1pfxc/edit?usp=sharing)

## Reading the meta data data file

First download the data from [this google folder](https://drive.google.com/drive/folders/1FgAS3UU0EfdKVqxgSc3gn6nHh84aC89-?usp=share_link). This includes a spreadsheet and pickle file (of the same data).

In [1]:
import pandas as pd

df = pd.read_pickle('./data/Kenya_hdx_tabular_data_metadata.pkl')

In [2]:
print(df.columns)
display(df)

Index(['resource_id', 'resource_name', 'resource_format', 'dataset_id',
       'dataset_name', 'dataset_org_title', 'dataset_last_modified',
       'dataset_tags', 'dataset_groups', 'dataset_total_res_downloads',
       'dataset_pageviews_last_14_days', 'file', 'type', 'dataset', 'sheet',
       'resource', 'num_rows', 'num_cols', 'columns', 'first_row',
       'has_hxl_header', 'first_nrows'],
      dtype='object')

,resource_id,resource_name,resource_format,dataset_id,dataset_name,dataset_org_title,dataset_last_modified,dataset_tags,dataset_groups,dataset_total_res_downloads,...,type,dataset,sheet,resource,num_rows,num_cols,columns,first_row,has_hxl_header,first_nrows
0,d22eb105-cda9-4060-9e98-8540ef06b942,Climate_Change_Opinion_Survey_Aggregated_06252...,XLSX,dc9f2ca4-8b62-4747-89b1-db426ce617a0,climate-change-opinion-survey,Data for Good at Meta (previously Facebook),2022-06-28T19:47:29.149259,"[{'display_name': 'climate-weather', 'id': '6f...","[{'description': '', 'display_name': 'Albania'...",1241,...,xlsx,"{'archived': False, 'batch': '35798ee2-2a13-4b...",climate_worry,{'alt_url': 'https://data.humdata.org/dataset/...,6,32,"['climate_worry', 'Argentina', 'Australia', 'B...","['Very worried', 54, 32, 58, 34, 65, 68, 17, 1...",False,"{""climate_worry"":{""0"":""Very worried"",""1"":""Some..."
1,d22eb105-cda9-4060-9e98-8540ef06b942,Climate_Change_Opinion_Survey_Aggregated_06252...,XLSX,dc9f2ca4-8b62-4747-89b1-db426ce617a0,climate-change-opinion-survey,Data for Good at Meta (previously Facebook),2022-06-28T19:47:29.149259,"[{'display_name': 'climate-weather', 'id': '6f...","[{'description': '', 'display_name': 'Albania'...",1241,...,xlsx,"{'archived': False, 'batch': '35798ee2-2a13-4b...",harm_personally,{'alt_url': 'https://data.humdata.org/dataset/...,7,32,"['harm_personally', 'Argentina', 'Australia', ...","['A great deal', 38, 19, 56, 18, 58, 55, 4, 17...",False,"{""harm_personally"":{""0"":""A great deal"",""1"":""A ..."
2,d22eb105-cda9-4060-9e98-8540ef06b942,Climate_Change_Opinion_Survey_Aggregated_06252...,XLSX,dc9f2ca4-8b62-4747-89b1-db426ce617a0,climate-change-opinion-survey,Data for Good at Meta (previously Facebook),2022-06-28T19:47:29.149259,"[{'display_name': 'climate-weather', 'id': '6f...","[{'description': '', 'display_name': 'Albania'...",1241,...,xlsx,"{'archived': False, 'batch': '35798ee2-2a13-4b...",harm_future_gen,{'alt_url': 'https://data.humdata.org/dataset/...,7,32,"['harm_future_gen', 'Argentina', 'Australia', ...","['A great deal', 68, 61, 74, 64, 77, 80, 33, 3...",False,"{""harm_future_gen"":{""0"":""A great deal"",""1"":""A ..."
3,d22eb105-cda9-4060-9e98-8540ef06b942,Climate_Change_Opinion_Survey_Aggregated_06252...,XLSX,dc9f2ca4-8b62-4747-89b1-db426ce617a0,climate-change-opinion-survey,Data for Good at Meta (previously Facebook),2022-06-28T19:47:29.149259,"[{'display_name': 'climate-weather', 'id': '6f...","[{'description': '', 'display_name': 'Albania'...",1241,...,xlsx,"{'archived': False, 'batch': '35798ee2-2a13-4b...",climate_importance,{'alt_url': 'https://data.humdata.org/dataset/...,7,32,"['climate_importance', 'Argentina', 'Australia...","['Extremely important', 18, 25, 36, 22, 30, 31...",False,"{""climate_importance"":{""0"":""Extremely importan..."
4,d22eb105-cda9-4060-9e98-8540ef06b942,Climate_Change_Opinion_Survey_Aggregated_06252...,XLSX,dc9f2ca4-8b62-4747-89b1-db426ce617a0,climate-change-opinion-survey,Data for Good at Meta (previously Facebook),2022-06-28T19:47:29.149259,"[{'display_name': 'climate-weather', 'id': '6f...","[{'description': '', 'display_name': 'Albania'...",1241,...,xlsx,"{'archived': False, 'batch': '35798ee2-2a13-4b...",gov_priority,{'alt_url': 'https://data.humdata.org/dataset/...,6,32,"['gov_priority', 'Argentina', 'Australia', 'Br...","['Very high', 48, 47, 54, 42, 66, 61, 21, 28, ...",False,"{""gov_priority"":{""0"":""Very high"",""1"":""High"",""2..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1802,d22eb105-cda9-4060-9e98-8540ef06b942,Climate_Change_Opinion_Survey_Aggregated_06252...,XLSX,dc9f2ca4-8b62-4747-89b1-db426ce617a0,climate-change-opinion-survey,Data for Good at Meta (previously Facebook),2022-06-28T19:47:29.149259,"[{'display_name': 'climate-weather', 'id': '6f...","[{'description': '', 'display_name': 'Albania'...",1241,...,xlsx,"{'archived': False, 'batch': '35798ee2-2a13-4b...",Readme,{'alt_url': 'https://data.humdata.org/dataset/...,15,3,"['Climate Change Opinion Survey', 'Climate Cha...","[nan, nan, nan]",False,"{""Climate Change Opinion Survey"":{""0"":null,""1""..."
1803,d22eb105-cda9-4060-9e98-8540ef06b942,Climate_Change_Opinion_Survey_Aggregated_06252...,XLSX,dc9f2ca4-8b62-4747-89b1-db426ce617a0,climate-change-opinion-survey,Data for Good at Meta (previously Facebook),2022-06-28T19:47:29.149259,"[{'display_name': 'climate-weather', 'id': '6f...","[{'description': '', 'display_name': 'Albania'...",1241,...,xlsx,"{'archived': False, 'batch': '35798ee2-2a13-4b...",Codebook,{'alt_url': 'https://data.humdata.org/dataset/...,26,4,"['Variable', 'Question Text', 'Response Catego...","['climate_awareness', 'How much do you know ab...",False,"{""Variable"":{""0"":""climate_awareness"",""1"":""clim..."
1804,d22eb105-cda9-4060-9e98-8540ef06b942,Climate_Change_Opinion_Survey_Aggregated_06252...,XLSX,dc9f2ca4-8b62-4747-89b1-db426ce617a0,climate-change-opinion-survey,Data for Good at Meta (previously Facebook),2022-06-28T19:47:29.149259,"[{'display_name': 'climate-weather', 'id': '6f...","[{'description': '', 'display_name': 'Albania'...",1241,...,xlsx,"{'archived': False, 'batch': '35798ee2-2a13-4b...",climate_awareness,{'alt_url': 'https://data.humdata.org/dataset/...,6,32,"['climate_awareness', 'Argentina', 'Australia'...","['I have never heard of it', 11, 2, 4, 2, 13, ...",False,"{""climate_awareness"":{""0"":""I have never heard ..."
1805,d22eb105-cda9-4060-9e98-8540ef06b942,Climate_Change_Opinion_Survey_Aggregated_06252...,XLSX,dc9f2ca4-8b62-4747-89b1-db426ce617a0,climate-change-opinion-survey,Data for Good at Meta (previously Facebook),2022-06-28T19:47:29.149259,"[{'display_name': 'climate-weather', 'id': '6f...","[{'description': '', 'display_name': 'Albania'...",1241,...,xlsx,"{'archived': False, 'batch': '35798ee2-2a13-4b...",climate_happening,{'alt_url': 'https://data.humdata.org/dataset/...,5,32,"['climate_happening', 'Argentina', 'Australia'...","['Yes', 90, 84, 92, 89, 90, 94, 87, 79, 91, 89...",False,"{""climate_happening"":{""0"":""Yes"",""1"":""No"",""2"":""..."
1806,d22eb105-cda9-4060-9e98-8540ef06b942,Climate_Change_Opinion_Survey_Aggregated_06252...,XLSX,dc9f2ca4-8b62-4747-89b1-db426ce617a0,climate-change-opinion-survey,Data for Good at Meta (previously Facebook),2022-06-28T19:47:29.149259,"[{'display_name': 'climate-weather', 'id': '6f...","[{'description': '', 'display_name': 'Albania'...",1241,...,xlsx,"{'archived': False, 'batch': '35798ee2-2a13-4b...",climate_beliefs,{'alt_url': 'https://data.humdata.org/dataset/...,7,32,"['climate_beliefs', 'Argentina', 'Australia', ...","['Caused mostly by human activities', 56, 50, ...",False,"{""climate_beliefs"":{""0"":""Caused mostly by huma..."

As a reminder, [HDX](https://data.humdata.org/) has datasets (basically the pages you see there), and then each file is a 'resource'. Fields from these are included in the table, but there are some fields which weren't parsed out. You can access the full dataset and resource objects records for each using these columns. As they are not true JSON, you will need to use `ast.literal_eval` to convert them todictionaries.

In [13]:
import ast

ast.literal_eval(df.loc[10, 'dataset'])

ast.literal_eval(df.loc[10, 'resource'])

{'alt_url': 'https://data.humdata.org/dataset/dc9f2ca4-8b62-4747-89b1-db426ce617a0/resource/d22eb105-cda9-4060-9e98-8540ef06b942/download/',
 'cache_last_updated': None,
 'cache_url': None,
 'created': '2021-06-24T19:32:46.284472',
 'datastore_active': False,
 'description': 'Survey data and codebook included. The survey was fielded on Facebook between February 17, 2021 and March 3, 2021.',
 'download_url': 'https://data.humdata.org/dataset/dc9f2ca4-8b62-4747-89b1-db426ce617a0/resource/d22eb105-cda9-4060-9e98-8540ef06b942/download/climate_change_opinion_survey_aggregated_06252021.xlsx',
 'format': 'XLSX',
 'hash': '',
 'hdx_rel_url': '/dataset/dc9f2ca4-8b62-4747-89b1-db426ce617a0/resource/d22eb105-cda9-4060-9e98-8540ef06b942/download/climate_change_opinion_survey_aggregated_06252021.xlsx',
 'id': 'd22eb105-cda9-4060-9e98-8540ef06b942',
 'last_modified': '2021-06-24T19:32:46.051095',
 'metadata_modified': '2023-03-03T04:40:35.050119',
 'microdata': False,
 'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
 'mimetype_inner': None,
 'name': 'Climate_Change_Opinion_Survey_Aggregated_06252021.xlsx',
 'originalHash': 490578609,
 'package_id': 'dc9f2ca4-8b62-4747-89b1-db426ce617a0',
 'pii': 'false',
 'pii_predict_score': 0.8723814453693705,
 'pii_report_flag': 'OK',
 'pii_report_id': '/resources/d22eb105-cda9-4060-9e98-8540ef06b942/pii.2021-06-24T19-32-49.main.json',
 'pii_timestamp': '2021-06-24T19:33:26.401000',
 'position': 1,
 'resource_type': 'file.upload',
 'size': 62815,
 'state': 'active',
 'url': 'https://data.humdata.org/dataset/dc9f2ca4-8b62-4747-89b1-db426ce617a0/resource/d22eb105-cda9-4060-9e98-8540ef06b942/download/climate_change_opinion_survey_aggregated_06252021.xlsx',
 'url_type': 'upload',
 'dataset_name': 'climate-change-opinion-survey'}

The data contains excerpts of the first few rows. The data in the table is a string, so it needs to be converted to JSON then pandas. 

**Note:** This is the unprocessed table data. For Excel files it can be a bit strange due to blank header rows and merged cells

In [8]:
import json

display(pd.DataFrame(json.loads(df.loc[0, 'first_nrows'])))

,climate_worry,Argentina,Australia,Brazil,Canada,Colombia,Costa Rica,Czech Republic,Egypt,France,...,Russia,Saudi Arabia,South Africa,Spain,Taiwan,Thailand,Turkey,United Kingdom,United States,Vietnam
0,Very worried,54,32,58,34,65,68,17,19,48,...,25,34,54,46,30,16,48,27,32,46
1,Somewhat worried,34,40,28,44,25,24,52,32,37,...,44,26,24,43,54,55,37,49,34,43
2,Not very worried,8,17,9,15,5,5,22,23,9,...,20,18,13,8,14,22,8,17,18,9
3,Not at all worried,4,12,4,8,3,2,9,26,5,...,11,20,7,3,2,6,6,7,16,2
4,Refused,0,0,1,0,1,1,0,1,0,...,0,2,2,0,0,1,1,0,0,1
5,(Unweighted Base),2450,2668,2093,2888,2040,2464,2431,1394,2339,...,2568,952,1512,2319,1918,1442,1712,2587,13555,1263